// Frontend/src/components/mindmap/MindMeisterNode.jsx

import { useState, useCallback, useEffect, useRef, memo } from 'react'
import { Handle, Position } from 'reactflow'
import { PlusCircleIcon } from '@heroicons/react/24/solid'
import { usePdfViewerStore } from '../../stores/pdfViewerStore'

const MindMeisterNode = memo(({ data, id, selected, dragging }) => {
  const [isEditing, setIsEditing] = useState(false)
  const [localLabel, setLocalLabel] = useState(data.label)
  const [showAnchors, setShowAnchors] = useState(false)
  const [noSourceMsg, setNoSourceMsg] = useState('')   // brief tooltip text
  const inputRef = useRef(null)
  const isComposingRef = useRef(false)
  const editingSetByDataRef = useRef(false)

  // PDF viewer panel store
  const showPdfViewer = usePdfViewerStore((s) => s.show)

  const isReadOnly = data.isReadOnly || false
  const level = data.level || 0
  const side = data.side
  const isRoot = data.isRoot || id === 'root-node'
  const autoAlign = data.autoAlign !== false
  const isCreatingConnection = data.isCreatingConnection || false
  const pdfSource = data.pdfSource || null
  const aiSource  = data.aiSource  || null

  // Styling props
  const color        = data.color        || '#3b82f6'
  const textColor    = data.textColor    || (level === 0 ? '#1f2937' : '#ffffff')
  const fontSize     = data.fontSize     || (level === 0 ? '20px' : level === 1 ? '16px' : '14px')
  const fontWeight   = data.fontWeight   || (level === 0 ? 'bold'  : level === 1 ? '600'  : '500')
  const borderRadius = data.borderRadius || (level === 0 ? '12px'  : level === 1 ? '20px' : '16px')
  const fontFamily   = data.fontFamily   || 'inherit'
  const transform    = data.transform    || 'none'
  const bold         = data.bold         || (level === 0)
  const italic       = data.italic       || false
  const underline    = data.underline    || false

  // Sync label when remote update arrives
  useEffect(() => { setLocalLabel(data.label) }, [data.label])

  // Auto-focus when freshly created
  useEffect(() => {
    if (data.editing && !isReadOnly && !editingSetByDataRef.current) {
      editingSetByDataRef.current = true
      setTimeout(() => {
        setIsEditing(true)
        if (data.onEditingChange) data.onEditingChange(true)
        setTimeout(() => {
          const node = data.yNodes.get(id)
          if (node && node.editing) data.yNodes.set(id, { ...node, editing: false })
        }, 100)
      }, 50)
    }
  }, [data.editing, id, data.yNodes, isReadOnly, data.onEditingChange])

  // Focus input
  useEffect(() => {
    if (isEditing && inputRef.current) {
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          if (inputRef.current) { inputRef.current.focus(); inputRef.current.select() }
        })
      })
    }
  }, [isEditing])

  const handleDoubleClick = () => {
    if (isReadOnly) return
    setIsEditing(true)
    if (data.onEditingChange) data.onEditingChange(true)
  }

  const handleBlur = useCallback(() => {
    if (isComposingRef.current) return
    setIsEditing(false)
    editingSetByDataRef.current = false
    if (data.onEditingChange) data.onEditingChange(false)
    if (data.yNodes) {
      const node = data.yNodes.get(id)
      if (node) {
        const finalLabel = localLabel.trim()
          ? localLabel.trim()
          : (isRoot ? node.label : 'New Node')
        data.yNodes.set(id, { ...node, label: finalLabel })
      }
    }
  }, [id, localLabel, data, isRoot])

  const handleCompositionStart = () => { isComposingRef.current = true }
  const handleCompositionEnd   = (e) => { isComposingRef.current = false; setLocalLabel(e.target.value) }

  const handleKeyDown = (e) => {
    if (isComposingRef.current) return
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleBlur() }
    if (e.key === 'Escape') {
      setLocalLabel(data.label)
      setIsEditing(false)
      editingSetByDataRef.current = false
      if (data.onEditingChange) data.onEditingChange(false)
    }
    if (e.key === 'Tab') e.stopPropagation()
  }

  const handleMouseEnter = () => { if (isCreatingConnection) setShowAnchors(true) }
  const handleMouseLeave = () => { setShowAnchors(false) }

  const handleAnchorClick = (anchorId) => (e) => {
    e.stopPropagation()
    if (data.onAnchorClick) data.onAnchorClick(id, anchorId, e)
  }

  // ── SOURCE CLICK HANDLERS ──────────────────────────────────────────────────
  const handlePdfSourceClick = useCallback((e) => {
    e.stopPropagation()
    if (!pdfSource) return
    showPdfViewer(
      pdfSource.page ?? null,
      pdfSource.text ?? null,
      pdfSource.chunkIndex ?? null
    )
  }, [pdfSource, showPdfViewer])

  const handleAiSourceClick = useCallback((e) => {
    e.stopPropagation()
    const sources = aiSource?.sources || []

    if (sources.length === 0) {
      // Node was generated by AI but no grounding URL was returned
      showBriefMsg('No web source for this node')
      return
    }

    const source = sources[0]
    if (!source?.url) {
      showBriefMsg('Source URL unavailable')
      return
    }

    let url = source.url.trim()
    // Ensure absolute URL
    if (!url.startsWith('http')) {
      showBriefMsg('Source URL invalid')
      return
    }

    // Append Text Fragment for Chrome/Edge automatic highlight+scroll
    if (source.searchText) {
      const encoded = encodeURIComponent(source.searchText.trim())
      url += `#:~:text=${encoded}`
    }

    window.open(url, '_blank', 'noopener,noreferrer')
  }, [aiSource])

  const showBriefMsg = (msg) => {
    setNoSourceMsg(msg)
    setTimeout(() => setNoSourceMsg(''), 2200)
  }

  // ── NODE STYLE ─────────────────────────────────────────────────────────────
  const getNodeStyle = () => {
    const style = {
      backgroundColor: data.background || color,
      background:      data.background || color,
      color:           textColor,
      fontSize,
      fontWeight:      bold ? 'bold' : fontWeight,
      fontStyle:       italic ? 'italic' : 'normal',
      textDecoration:  underline ? 'underline' : 'none',
      fontFamily,
      borderRadius,
      transform,
      transition:      'all 0.2s ease',
      cursor:          'pointer',
      border:          data.border    || 'none',
      boxShadow:       data.boxShadow || (level === 0 ? '0 4px 12px rgba(0,0,0,0.1)' : '0 2px 8px rgba(0,0,0,0.08)'),
      padding:         data.padding   || (level === 0 ? '16px 24px' : level === 1 ? '12px 20px' : '8px 16px'),
      letterSpacing:   data.letterSpacing || 'normal',
      filter:          data.filter    || 'none',
      position:        'relative',
      minWidth:        level === 0 ? '180px' : level === 1 ? '140px' : '100px',
      maxWidth:        '350px'
    }

    if (aiSource) {
      style.borderLeft = '3px solid rgba(139,92,246,0.6)'
    }

    return style
  }

  const nodeStyle         = getNodeStyle()
  const addButtonPosition = side === 'left' ? 'left' : 'right'
  const hasBoth           = pdfSource && aiSource

  return (
    <div
      className="relative group"
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
    >
      <div
        className={[
          'cursor-pointer',
          selected  ? 'ring-4 ring-primary-400 ring-opacity-50' : '',
          !isReadOnly ? 'hover:shadow-lg hover:scale-105' : '',
          dragging  ? 'opacity-50' : '',
        ].join(' ')}
        style={nodeStyle}
        onDoubleClick={handleDoubleClick}
      >
        {/* ── PDF source badge ───────────────────────────────────────── */}
        {pdfSource && (
          <button
            onClick={handlePdfSourceClick}
            title={pdfSource.page ? `View PDF — page ${pdfSource.page}` : 'View PDF source'}
            style={{
              position: 'absolute',
              top: '4px',
              right: hasBoth ? '26px' : '4px',
              width: '18px', height: '18px',
              borderRadius: '4px',
              background: 'rgba(255,255,255,0.25)',
              border: '1px solid rgba(255,255,255,0.4)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              cursor: 'pointer', padding: 0, fontSize: '10px',
            }}
          >
            📄
          </button>
        )}

        {/* ── AI source badge ────────────────────────────────────────── */}
        {aiSource && (
          <>
            <button
              onClick={handleAiSourceClick}
              title={
                aiSource?.sources?.length > 0
                  ? 'Open web source in new tab'
                  : 'AI-generated — no web source'
              }
              style={{
                position: 'absolute',
                top: '4px', right: '4px',
                width: '18px', height: '18px',
                borderRadius: '4px',
                background: 'rgba(139,92,246,0.25)',
                border: '1px solid rgba(139,92,246,0.4)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                cursor: aiSource?.sources?.length > 0 ? 'pointer' : 'default',
                padding: 0, fontSize: '10px',
              }}
            >
              ✨
            </button>

            {/* Brief "no source" tooltip */}
            {noSourceMsg && (
              <div style={{
                position: 'absolute',
                top: '-30px',
                right: '0',
                background: 'rgba(0,0,0,0.75)',
                color: '#fff',
                padding: '3px 8px',
                borderRadius: '6px',
                fontSize: '11px',
                whiteSpace: 'nowrap',
                pointerEvents: 'none',
                zIndex: 20,
                animation: 'fadeIn 0.15s ease',
              }}>
                {noSourceMsg}
              </div>
            )}
          </>
        )}

        {/* ── Anchors (connection mode) ──────────────────────────────── */}
        {isCreatingConnection && showAnchors && (
          <>
            {['top', 'right', 'bottom', 'left'].map(pos => (
              <div
                key={pos}
                onClick={handleAnchorClick(pos)}
                title={pos}
                className={[
                  'absolute w-6 h-6 bg-blue-500 border-2 border-white rounded-full',
                  'cursor-pointer hover:bg-blue-600 hover:scale-110 transition z-10',
                  'flex items-center justify-center text-white text-xs font-bold',
                  pos === 'top'    ? '-top-3 left-1/2 -translate-x-1/2'    : '',
                  pos === 'right'  ? '-right-3 top-1/2 -translate-y-1/2'   : '',
                  pos === 'bottom' ? '-bottom-3 left-1/2 -translate-x-1/2' : '',
                  pos === 'left'   ? '-left-3 top-1/2 -translate-y-1/2'    : '',
                ].join(' ')}
              >
                +
              </div>
            ))}
          </>
        )}

        {/* ── Node content ───────────────────────────────────────────── */}
        {isEditing && !isReadOnly ? (
          <input
            ref={inputRef}
            type="text"
            value={localLabel}
            onChange={(e) => setLocalLabel(e.target.value)}
            onBlur={handleBlur}
            onKeyDown={handleKeyDown}
            onCompositionStart={handleCompositionStart}
            onCompositionEnd={handleCompositionEnd}
            className="w-full outline-none bg-transparent text-center"
            style={{
              color:          nodeStyle.color,
              fontSize:       nodeStyle.fontSize,
              fontWeight:     nodeStyle.fontWeight,
              fontStyle:      nodeStyle.fontStyle,
              textDecoration: nodeStyle.textDecoration,
              fontFamily:     nodeStyle.fontFamily,
            }}
          />
        ) : (
          <div
            className="text-center whitespace-pre-wrap break-words"
            style={{
              fontSize:       nodeStyle.fontSize,
              fontWeight:     nodeStyle.fontWeight,
              fontStyle:      nodeStyle.fontStyle,
              textDecoration: nodeStyle.textDecoration,
              fontFamily:     nodeStyle.fontFamily,
            }}
          >
            {localLabel || 'Empty'}
          </div>
        )}

        {/* ── React Flow Handles ─────────────────────────────────────── */}
        <Handle type="target" position={Position.Top}    id="target-top"    className="!opacity-0 !w-1 !h-1" />
        <Handle type="target" position={Position.Right}  id="target-right"  className="!opacity-0 !w-1 !h-1" />
        <Handle type="target" position={Position.Bottom} id="target-bottom" className="!opacity-0 !w-1 !h-1" />
        <Handle type="target" position={Position.Left}   id="target-left"   className="!opacity-0 !w-1 !h-1" />
        <Handle type="source" position={Position.Top}    id="source-top"    className="!opacity-0 !w-1 !h-1" />
        <Handle type="source" position={Position.Right}  id="source-right"  className="!opacity-0 !w-1 !h-1" />
        <Handle type="source" position={Position.Bottom} id="source-bottom" className="!opacity-0 !w-1 !h-1" />
        <Handle type="source" position={Position.Left}   id="source-left"   className="!opacity-0 !w-1 !h-1" />
      </div>

      {/* ── Add child button ──────────────────────────────────────────── */}
      {!isReadOnly && !isCreatingConnection && (
        <button
          onClick={(e) => { e.stopPropagation(); data.onAddChild?.(id) }}
          className="absolute top-1/2 -translate-y-1/2 opacity-0 group-hover:opacity-100 transition-all duration-200 hover:scale-110"
          style={{
            [addButtonPosition === 'left' ? 'left' : 'right']: '-16px',
            zIndex: 10,
          }}
          title="Add child node (Tab)"
        >
          <PlusCircleIcon className="w-8 h-8 drop-shadow-lg" style={{ color }} />
        </button>
      )}

      {/* ── Unlock indicator ────────────────────────────────────────── */}
      {!isRoot && !autoAlign && !dragging && (
        <div
          className="absolute -top-2 -right-2 w-6 h-6 bg-yellow-400 rounded-full flex items-center justify-center text-xs shadow-lg"
          title="Unlocked (draggable)"
        >
          🔓
        </div>
      )}
    </div>
  )
})

MindMeisterNode.displayName = 'MindMeisterNode'
export default MindMeisterNode